"""
Observability: metrics, health checks, performance monitoring.
"""

from quantlib_pro.observability.metrics import (
    METRICS_REGISTRY,
    calculations_total,
    calculation_duration,
    portfolio_value,
    portfolio_var,
    trades_executed,
    trade_slippage,
    data_quality_score,
    missing_data_points,
    cache_hits,
    cache_misses,
    errors_total,
    api_requests,
    api_latency,
    track_calculation,
    track_api_request,
    record_trade,
    record_cache_access,
    update_portfolio_metrics,
    record_data_quality,
    export_metrics,
    MetricSnapshot,
    get_metrics_snapshot,
    measure_time,
)
from quantlib_pro.observability.health import (
    HealthStatus,
    HealthCheckResult,
    SystemHealth,
    HealthChecker,
    register_health_check,
    check_health,
    get_health_checker,
    check_memory,
    check_disk,
    check_cpu,
    liveness_probe,
    readiness_probe,
    register_default_checks,
)
from quantlib_pro.observability.performance import (
    PerformanceMetrics,
    PerformanceMonitor,
    get_performance_monitor,
    monitor_performance,
    track_performance,
    profile_section,
    PerformanceTimer,
    time_function,
    benchmark,
)
from quantlib_pro.observability.profiler import (
    PerformanceMeasurement,
    PerformanceStats,
    PerformanceProfiler,
    PerformanceTarget,
    profile,
    get_profiler,
    print_profile_report,
    print_bottlenecks,
)
from quantlib_pro.observability.monitoring import (
    AlertLevel,
    MetricType,
    PerformanceBaseline,
    Alert,
    PerformanceMonitor as RealTimeMonitor,
    get_monitor,
    reset_monitor,
)

__all__ = [
    # Metrics
    "METRICS_REGISTRY",
    "calculations_total",
    "calculation_duration",
    "portfolio_value",
    "portfolio_var",
    "trades_executed",
    "trade_slippage",
    "data_quality_score",
    "missing_data_points",
    "cache_hits",
    "cache_misses",
    "errors_total",
    "api_requests",
    "api_latency",
    "track_calculation",
    "track_api_request",
    "record_trade",
    "record_cache_access",
    "update_portfolio_metrics",
    "record_data_quality",
    "export_metrics",
    "MetricSnapshot",
    "get_metrics_snapshot",
    "measure_time",
    # Health
    "HealthStatus",
    "HealthCheckResult",
    "SystemHealth",
    "HealthChecker",
    "register_health_check",
    "check_health",
    "get_health_checker",
    "check_memory",
    "check_disk",
    "check_cpu",
    "liveness_probe",
    "readiness_probe",
    "register_default_checks",
    # Performance
    "PerformanceMetrics",
    "PerformanceMonitor",
    "get_performance_monitor",
    "monitor_performance",
    "track_performance",
    "profile_section",
    "PerformanceTimer",
    "time_function",
    "benchmark",
    # Profiler
    "PerformanceMeasurement",
    "PerformanceStats",
    "PerformanceProfiler",
    "PerformanceTarget",
    "profile",
    "get_profiler",
    "print_profile_report",
    "print_bottlenecks",
    # Monitoring
    "AlertLevel",
    "MetricType",
    "PerformanceBaseline",
    "Alert",
    "RealTimeMonitor",
    "get_monitor",
    "reset_monitor",
]
